name: Run test matrix

on: [push]

jobs:
  both-scala-versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala: ["2.12.15", "2.13.8"]
        spark: ["3.3.0","3.2.1","3.2.0"]
    steps:
    - name: Test versions
      run: "echo scala: ${{ matrix.scala }}, spark: ${{ matrix.spark }}!"
      
  scala-version-2_12:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala: ["2.12.15"]
        spark: ["3.1.3", "3.1.2", "3.1.1", "3.1.0", "3.0.3", "3.0.2", "3.0.1", "3.0.0"]
    steps:
    - name: Test versions
      run: "echo scala: ${{ matrix.scala }}, spark: ${{ matrix.spark }}!"
