name: Run on Pull Request

# simple
# on: [push, pull_request]

# run on PRs against master
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Works
      run: echo "works"
